spring:
  application:
    name: stress-test-tomcat
  datasource:
    url: jdbc:postgresql://stress-test-postgres-db-tomcat:5432/stress
    username: root
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 80