apiVersion: v1
kind: Pod
metadata:
  name: stress-test-postgres-db-tomcat
  labels:
    app: stress-test-postgres-db-tomcat
spec:
  containers:
    - name: postgresql
      image: postgres:17.4-alpine
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: "root"
        - name: POSTGRES_PASSWORD
          value: "12345"
        - name: POSTGRES_DB
          value: "stress"
      volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgresql-data
      emptyDir: {}  # Volume temporário, dados serão apagados quando o pod for removido ou reiniciado
