apiVersion: v1
kind: Service
metadata:
  name: stress-tomcat-service
  namespace: default # Match the namespace of the Deployment
spec:
  selector:
    app: stress-tomcat-app # Match the labels of the Pods from the Deployment
  ports:
    - protocol: TCP
      port: 8000 # The port that the Service listens on
      targetPort: 80 # The port that the Pods are listening on
  type: LoadBalancer # Or NodePort/LoadBalancer as needed