name: CI - Build and Update Argo CD

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      - name: Docker login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Configurar Java 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: maven

      - name: Construir e testar aplicação
        run: mvn clean package
      - name: Set Image Version Variable
        run: echo "IMAGE_VERSION=${{ env.IMAGE_VERSION }}" >> $GITHUB_ENV
      - name: Build docker image
        run: docker build -t washington1995luiz/stress-test-tomcat:${{ env.IMAGE_VERSION }} .
      - name: Push image docker
        run: docker push washington1995luiz/stress-test-tomcat:${{ env.IMAGE_VERSION }}

  update-argocd:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      - name: Update Deployment YAML
        run: |
          sed -i "s|washington1995luiz/stress-test-tomcat:.*|washington1995luiz/stress-test-tomcat:${{ env.IMAGE_VERSION }}|g" k8s/application.yaml
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update image tag to ${{ env.IMAGE_VERSION }}"
          file_pattern: k8s/application.yaml